### ISSUE TITLE
Docker build not working on Windows 10

### ISSUE THREAD

**Issue by BuzzyLizzy** [intersystems-ib/iris-sample-rest-angular#4]
I have to learn Angular with IRIS, I follow instructions on this tutorial but the "docker-compose build" does not work on Windows 10, I get this error:
ERROR: Service 'backend' failed to build: image operating system "linux" cannot be used on this platform

I have Googled and tried everything advised, but nothing works. Is there any other way I can make this sample work?

**Comment by BuzzyLizzy** [comment]
I got it to work, I switched the Docker to Linux containers, but it would not switch, eventually I restarted the Docker and then it switched to Linux containers, now working.

**Comment by albertoft** [comment]
Great, glad to know you got it working. Thanks for reporting!
